FROM node:26-alpine

# Install pnpm
RUN npm install -g pnpm@10.34.5

WORKDIR /app

# Expose port
EXPOSE 3000

# Install dependencies and run dev server
CMD ["sh", "-c", "pnpm install && pnpm migrate && pnpm dev"]
